### ISSUE TITLE
Reducing Verbosity Terraform in Travis

### ISSUE THREAD

**Issue by carmat88** [kubenow/image#7]
Currently when building the image on GCE, during the post-processor we are running terraform. This produces a very verbose output even if `TF_LOG` is being set to a different value. The possible reason might be that terraform is being run within the `packer build` command.

**TO DO:** Investigation is necessary. Possibly opening an Issue on [Terraform](https://github.com/hashicorp/terraform/issues)

**Comment by mcapuccini** [comment]
Issues go to the main repo. I am going to disable them.
